version: '3.4'

services:
  shoppingapi:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: ShoppingAPI/Dockerfile

  shopping.client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: mongo

